---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  ansible-lint
  ansible-later
  yamllint .
platforms:
  - name: compile-gcc-centos7
    image: centos:7.9.2009
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
  config_options:
    stdout_callback: yaml
