---
name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: centos-7
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.8
        with:
          command: lint
